FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache \
    libpcap-dev \
    gcc \
    build-base

USER root

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=1 GOOS=linux go build -o /sniffer ./cmd/sniffer/main.go

USER root
CMD ["/sniffer"] 